//! Shared constants and types for health checks.

use std::path::{Path, PathBuf};

use ignore::WalkBuilder;

/// Directories to always skip, even if not in .gitignore.
pub const ALWAYS_SKIP: &[&str] = &[
    "node_modules",
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    ".tox",
    "dist",
    "build",
    ".next",
    ".nuxt",
    "target",           // Rust/Cargo, also general build output
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "env",
    ".egg-info",
    // Go / PHP (Composer)
    "vendor",
    // Java / Kotlin
    ".gradle",
    ".idea",
    "out",
    // C / C++
    "cmake-build-debug",
    "cmake-build-release",
    // Ruby
    ".bundle",
    // General
    ".cache",
    "coverage",
    ".coverage",
    ".terraform",
];

/// Source file extensions we care about for analysis.
pub const SOURCE_EXTENSIONS: &[&str] = &[
    // Python
    "py",
    // JavaScript / TypeScript
    "js", "ts", "jsx", "tsx", "mjs", "mts", "cjs", "cts",
    // Rust
    "rs",
    // Go
    "go",
    // C / C++
    "c", "h", "cpp", "hpp", "cc", "cxx", "hxx",
    // Java / Kotlin
    "java", "kt", "kts",
    // Ruby
    "rb",
    // PHP
    "php",
    // Swift
    "swift",
    // C#
    "cs",
];

/// Check if a directory entry should be skipped.
/// Checks both hardcoded names AND detects non-standard Python venvs
/// (by looking for pyvenv.cfg inside the directory).
pub fn should_skip(name: &str) -> bool {
    ALWAYS_SKIP.iter().any(|s| *s == name)
}

/// Extended skip check that also detects non-standard virtualenvs
/// by looking for `pyvenv.cfg`. Use in filter_entry where you have
/// access to the full path.
pub fn should_skip_entry(entry: &ignore::DirEntry) -> bool {
    if let Some(name) = entry.file_name().to_str() {
        if should_skip(name) {
            return true;
        }
    }
    // Detect non-standard Python venvs (e.g. tg-session-env/)
    if entry.file_type().map(|ft| ft.is_dir()).unwrap_or(false) {
        if entry.path().join("pyvenv.cfg").exists() {
            return true;
        }
    }
    false
}

/// Recursively walk all nodes in a tree-sitter tree, calling f on each.
pub fn walk_nodes<F>(cursor: &mut tree_sitter::TreeCursor, f: &mut F)
where
    F: FnMut(tree_sitter::Node),
{
    f(cursor.node());
    if cursor.goto_first_child() {
        loop {
            walk_nodes(cursor, f);
            if !cursor.goto_next_sibling() {
                break;
            }
        }
        cursor.goto_parent();
    }
}

/// Normalize path separators to forward slashes (Windows compatibility).
pub fn normalize_path(path: &str) -> String {
    path.replace('\\', "/")
}

/// Return true if this file path looks like generated code, mock/test data,
/// seed fixtures, or a vendored third-party binary. Such files are not hand-
/// written and should be skipped from dead-code / monster / tech-debt checks.
pub fn is_generated_or_data_file(rel_path: &str) -> bool {
    let p = rel_path.replace('\\', "/");
    // Path segments that indicate autogenerated or data-only content.
    const GENERATED_SEGMENTS: &[&str] = &[
        "/generated/",
        "/__generated__/",
        "/generated-metadata/",
        "/mock-data/",
        "/mocks/",
        "/__mocks__/",
        "/dev-seeder/data/",
        "/fixtures/",
        "/.yarn/releases/",
        "/.yarn/plugins/",
        "/.yarn/sdks/",
    ];
    for seg in GENERATED_SEGMENTS {
        if p.contains(seg) || p.starts_with(&seg[1..]) {
            return true;
        }
    }
    // Well-known generated/bundled filename suffixes.
    let basename = p.rsplit('/').next().unwrap_or(&p);
    if basename.ends_with(".min.js")
        || basename.ends_with(".min.css")
        || basename.ends_with(".bundle.js")
        || basename.ends_with(".d.ts")
        || basename == ".pnp.cjs"
        || basename == ".pnp.loader.mjs"
    {
        return true;
    }
    // Seed data and generated constants (common NestJS / Nx convention).
    if basename.ends_with("-data-seeds.constant.ts")
        || basename.ends_with("-data-seeds.ts")
        || basename.ends_with(".generated.ts")
        || basename.ends_with(".gen.ts")
        || basename.ends_with(".g.ts")
    {
        return true;
    }
    // Yarn release binaries (yarn-4.x.y.cjs under .yarn/releases/ is caught
    // by the segment check, but allow freestanding yarn-*.cjs too).
    if basename.starts_with("yarn-") && basename.ends_with(".cjs") {
        return true;
    }
    false
}

/// Return true if a relative path looks like test code. Pattern shared by
/// duplicates, tech_debt, reusable, overengineering scanners.
pub fn is_test_path(rel_path: &str) -> bool {
    rel_path.contains("/test")
        || rel_path.starts_with("test")
        || rel_path.contains("/__tests__/")
}

/// One source file located by the walker. Owned data so callers can outlive
/// the underlying `WalkBuilder` iterator without lifetime juggling.
pub struct SourceFile {
    pub abs_path: PathBuf,
    /// Relative to the scan root, with forward-slash normalization.
    pub rel_path: String,
    /// Lowercase extension without the leading dot.
    pub ext: String,
}

/// Options for `collect_source_files`.
pub struct WalkOpts {
    /// Maximum directory depth, or `None` for unlimited.
    pub max_depth: Option<usize>,
    /// Skip generated/mock/seed/vendored files (default: true).
    pub skip_generated: bool,
    /// Allowed extensions. Defaults to `SOURCE_EXTENSIONS`.
    pub allowed_extensions: &'static [&'static str],
}

impl Default for WalkOpts {
    fn default() -> Self {
        Self {
            max_depth: None,
            skip_generated: true,
            allowed_extensions: SOURCE_EXTENSIONS,
        }
    }
}

/// Walk `root` and return every source file matching `opts`. Centralizes the
/// `WalkBuilder` boilerplate, extension filter, generated-file skip and path
/// normalization that every scanner used to repeat (~30 LOC × 7 scanners).
///
/// Files that fail to be relativized against `root` are silently dropped —
/// they cannot belong to the scanned tree by definition.
pub fn collect_source_files(root: &Path, opts: &WalkOpts) -> Vec<SourceFile> {
    let mut builder = WalkBuilder::new(root);
    builder
        .hidden(false)
        .git_ignore(true)
        .git_global(false)
        .git_exclude(true)
        .filter_entry(|entry| !should_skip_entry(entry));
    if let Some(depth) = opts.max_depth {
        builder.max_depth(Some(depth));
    }

    let mut out = Vec::new();
    for entry in builder.build().flatten() {
        let entry_path = entry.path();
        if !entry_path.is_file() {
            continue;
        }
        let Some(ext_raw) = entry_path.extension().and_then(|e| e.to_str()) else {
            continue;
        };
        // Compare case-insensitively so we don't miss `Foo.PY` etc.
        let ext_lower = ext_raw.to_ascii_lowercase();
        if !opts
            .allowed_extensions
            .iter()
            .any(|e| e.eq_ignore_ascii_case(&ext_lower))
        {
            continue;
        }
        let Ok(rel) = entry_path.strip_prefix(root) else {
            continue;
        };
        let rel_path = normalize_path(&rel.to_string_lossy());
        if opts.skip_generated && is_generated_or_data_file(&rel_path) {
            continue;
        }
        out.push(SourceFile {
            abs_path: entry_path.to_path_buf(),
            rel_path,
            ext: ext_lower,
        });
    }
    out
}
